FROM node:20.11.0

# Set the working directory
WORKDIR /sharedbuylists

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY ./ ./

# Expose the application port
EXPOSE 4200

# Start the application
CMD ["npm", "start"]