version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "4200:4200"
    depends_on:
      - angular

  angular:
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - "80:80"